#!/usr/bin/env bash
# This is a script that displays numbers from 1 to 100
i=1
while [[ $i -le 100 ]]
do
	f=$(( i % 3 ))
	b=$(( i % 5 ))
	if [[ $f == 0 ]] && [[ $b == 0 ]]
	then
		echo "FizzBuzz"
	elif [[ $b == 0 ]]
	then
		echo "Buzz"
	elif [[ $f == 0 ]]
	then
		echo "Fizz"
	else
		echo $i
	fi
	(( i++ ))
done
