#!/bin/bash
# Configures a ufw firewall to block all incoming traffic
apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable
sudo ufw default deny incoming
ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
